motorola <- read.csv("C:/Users/jozek/OneDrive/Studia - semestr 1/Analiza Procesów Uczenia/apu/apu/lab3/motorola.csv")
traininginput <-  as.data.frame(motorola[,c(4,5,6)])
trainingoutput <- as.data.frame(motorola[,7])
trainingdata <- cbind(traininginput,trainingoutput)
colnames(trainingdata) <- c("pamiec_RAM","pamiec_Wbudowana","aparat_Foto","cena")
net.price <- neuralnet(cena~pamiec_RAM+pamiec_Wbudowana+aparat_Foto,trainingdata, hidden=50, threshold=100)
print(net.price)
plot(net.price)
testdata <- as.data.frame(motorola[,c(4,5,6)])
net.results <- compute(net.price, testdata)
print(net.results$net.result)
